### ISSUE TITLE
Don't look for the executable at package load time

### ISSUE THREAD

**Issue by astoff** [shaohme/flymake-yamllint#1]
It's better not to call (executable-find "yamllint") at load time. This is incompatible with "project environment management" packages like direnv, envrc, buffer-env and various virtualenv integration packages which change the exec-path during runtime. I suggest renaming flymake-yamllint-path to flymake-yamllint-program and calling executable-find only inside the backend function.

Also, this check is already made by executable-find anyway: 

https://github.com/shaohme/flymake-yamllint/blob/22690dd862089f470980cceea06153682a397b7a/flymake-yamllint.el#L60

**Comment by shaohme** [comment]
Good idea. I'll look into it.

**Comment by shaohme** [comment]
@astoff Please review branch to see if it was what you meant.

**Comment by astoff** [comment]
Yes, that looks right.
