### ISSUE TITLE
Can't start yamllint linter

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [shaohme/flymake-yamllint#3]
# Description

I have `flymake-yamllint` installed and `yamllint` too. But when I open some `yml` file I obtain an error: `Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)`.

![image](https://user-images.githubusercontent.com/42812113/169225253-4310772c-e7ce-40d6-9205-d9c3863671c9.png)

When I run `flymake-start` I get: `Wrong type argument: hash-table-p, nil`.

# Expected behavior

Obtain several errors:

```
test.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  comment not indented like content  (comments-indentation)
  3:9       error    no new line character at the end of file  (new-line-at-end-of-file)
  3:6       error    trailing spaces  (trailing-spaces)
```

for the following file:

```yml
aa: "123"
b: 4
# fdf   
```

# Config

My `~/.emacs` file:

```emacs
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(add-hook 'yaml-mode-hook 'flymake-yamllint-setup)
(flymake-mode)

(package-initialize)

(when (version<= "26.0.50" emacs-version)
  (global-display-line-numbers-mode))

(setq completion-styles '(basic partial-completion emacs22 substring))

;; Interface customization
(set-face-foreground 'default "#660066")
```

**Comment by shaohme** [comment]
i'm not sure of the problem, but here is a few suggestions to try out.

1. when in the yml buffer, try inspect ```C-h v``` the ```flymake-diagnostic-functions``` variable. it should contain ``` flymake-yamllint ``` function.
 
2. check the ```yamllint``` executable is reachable to emacs. like inspecting the result of evaluating ```(executable-find "yamllint")```

3. try enable more verbose error debugging. like ```M-x toggle-debug-on-error``` and see if the traces makes sense to you, if any error at all.

**Comment by EmilyGraceSeville7cf** [comment]
1. `flymake-diagnostic-functions` = (flymake-proc-legacy-flymake)
2. `(executable-find "yamllint")` = "/usr/bin/yamllint"
3. After `M-x toggle-debug-on-error` when I use `flymake-start` I see:

```
  1 Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  2   gethash(flymake-proc-legacy-flymake nil)
  3   #f(compiled-function (backend) #<bytecode 0x4e275d>)(flymake-proc-legacy-flymake)
  4   run-hook-wrapped(#f(compiled-function (backend) #<bytecode 0x4e275d>) flymake-proc-legacy-flymake)
  5   flymake-start(nil nil)
  6   funcall-interactively(flymake-start nil nil)
  7   call-interactively(flymake-start record nil)
  8   command-execute(flymake-start record)
  9   execute-extended-command(nil "flymake-start" "flymake-st")
 10   funcall-interactively(execute-extended-command nil "flymake-start" "flymake-st")
 11   call-interactively(execute-extended-command nil nil)
 12   command-execute(execute-extended-command)
```

**Comment by shaohme** [comment]
It seems ```flymake-diagnostic-functions``` does not contain the correct flymake checker ```flymake-yamllint``` hence why the buffer does not get lintet.

In my emacs config I don't enable ```flymake-mode``` right away, but only in specific modes, like so:
```
...
(require 'flymake-yamllint)
...
(add-hook 'yaml-mode-hook #'flymake-yamllint-setup)
(add-hook 'yaml-mode-hook #'flymake-mode)
...
```
Maybe the ```flymake-yamllint``` package does not get loaded, or in the wrong order ?

**Comment by EmilyGraceSeville7cf** [comment]
![image](https://user-images.githubusercontent.com/42812113/169252491-b91ba127-6862-468f-85bd-f8f3e51d154c.png)

Plugin is installed but `(require 'flymake-yamllint)` command fails with:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "flymake-yamllint")
  require(flymake-yamllint)
  eval-buffer(#<buffer  *load*> nil "/home/emilyseville7cfg/.emacs" nil t)  ; Reading at buffer position 125
  load-with-code-conversion("/home/emilyseville7cfg/.emacs" "/home/emilyseville7cfg/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1baed5>)()
  command-line()
  normal-top-level()
```

P.S. I've used your three commands from the last comment.

**Comment by shaohme** [comment]
I noticed in your ```.emacs``` you have ```(package-initialize)``` after adding the hooks. Try invoking it before your customizations, but after your ```package``` configurations, like so:
```
...
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(package-initialize) <---

(require 'flymake-yamllint)

(add-hook 'yaml-mode-hook #'flymake-yamllint-setup)
(add-hook 'yaml-mode-hook #'flymake-mode)

(when (version<= "26.0.50" emacs-version)
  (global-display-line-numbers-mode))
...
```

**Comment by EmilyGraceSeville7cf** [comment]
Why `flymake-start` still fails with `Wrong type argument: hash-table-p, nil`? 🤔 No other errors happen now.

**Comment by shaohme** [comment]
Not sure. 

According to my emacs (28.1) source code, when using ```flymake-proc-legacy-flymake```  it seems the buffer needs to have a file name, the file needs to be writable, and file extension allowed in ```flymake-proc-allowed-file-name-masks``` and/or ```flymake-proc-ignored-file-name-regexps```.

If you explicitly don't want ```flymake-proc-legacy-flymake``` invoked, you can remove it like so:
```
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

**Comment by EmilyGraceSeville7cf** [comment]
I use GNU Emacs 26.3. When I add `(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)` no error happens but also no linter errors displayed.

**Comment by shaohme** [comment]
Is ```flymake-yamllint``` still in ```flymake-diagnostic-functions``` list when visiting a YAML buffer?

**Comment by EmilyGraceSeville7cf** [comment]
No, it is `nil`.

```emacs
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(package-initialize)

(require 'flymake-yamllint)

(add-hook 'yaml-mode-hook #'flymake-yamllint-setup)
(add-hook 'yaml-mode-hook #'flymake-mode)
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)

(when (version<= "26.0.50" emacs-version)
  (global-display-line-numbers-mode))

(setq completion-styles '(basic partial-completion emacs22 substring))

;; Interface customization
(set-face-foreground 'default "#660066")
```

**Comment by shaohme** [comment]
That is weird. Maybe ```flymake-yamllint-setup``` doesn't do its job. I haven't tested this in emacs 26.3. Only 27.1 and newer. Maybe I should try it out on an older version ...

**Comment by EmilyGraceSeville7cf** [comment]
I will try in the latest version. Maybe it help. But I am not sure. 🤣

**Comment by shaohme** [comment]
I have trouble building 26.x on my machine. 

If it works with 27.1 or newer, and you're willing to upgrade, let me know.

**Comment by EmilyGraceSeville7cf** [comment]
The same problem happens in [Emacs 28.1](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs). Can you reproduce this problem?

**Comment by shaohme** [comment]
I have overlooked a detail in your first screenshot :-| .
The file is opened in ```Fundamental``` mode, which does not load any of the hooks in your config. The buffer should load in ```yaml-mode```.

Did you install ```yaml-mode``` at all?

**Comment by EmilyGraceSeville7cf** [comment]
It was not installed when I created this issue. But now everything works:

![image](https://user-images.githubusercontent.com/42812113/169285162-df8a177a-68a2-44c2-a599-7eb25cab7846.png)

Thanks! ❤️

**Comment by EmilyGraceSeville7cf** [comment]
@shaohme, I suggest note about `yaml-mode` installation in README.

**Comment by shaohme** [comment]
> It was not installed when I created this issue. But now everything works:
> 
> ![image](https://user-images.githubusercontent.com/42812113/169285162-df8a177a-68a2-44c2-a599-7eb25cab7846.png)
> 
> Thanks! heart

Glad you made it work.

**Comment by shaohme** [comment]
> @shaohme, I suggest note about `yaml-mode` installation in README.

Yeah, I thought about that too. I'll add it now.
